export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";

export const FETCH_WEATHER_FAV_START = "FETCH_WEATHER_FAV_START";
export const FETCH_WEATHER_FAV_SUCCESS = "FETCH_WEATHER_FAV_SUCCESS";
export const FETCH_WEATHER_FAV_FAIL = "FETCH_WEATHER_FAV_FAIL";

export const DELETE_FAV_CITY = "DELETE_FAV_CITY";
