export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";

export const FETCH_FAVORITE_WEATHER_START = "FETCH_FAVORITE_WEATHER_START";
export const FETCH_FAVORITE_WEATHER_SUCCESS = "FETCH_FAVORITE_WEATHER_SUCCESS";
export const FETCH_FAVORITE_WEATHER_FAIL = "FETCH_FAVORITE_WEATHER_FAIL";

export const DELETE_FAVORITE_CITY = "DELETE_FAVORITE_CITY";
export const ADD_FAVORITE_CITY = "ADD_FAVORITE_CITY";
